namespace Dgmjr.AspNetCore.TagHelpers.Enumerations;

public enum InputType
{
    Text,
    text = Text,
    Password,
    password = Password,
    Email,
    email = Email,
    Number,
    number = Number,
    Url,
    url = Url,
    Search,
    search = Search,
    Tel,
    tel = Tel,
    Date,
    date = Date,
    Time,
    time = Time,
    DateTime,
    datetime = DateTime,
    DateTimeLocal,
    datetimelocal = DateTimeLocal,
    Month,
    month = Month,
    Week,
    week = Week,
    Color,
    color = Color,
    File,
    file = File,
    Range,
    range = Range,
    Hidden,
    hidden = Hidden,
    Image,
    image = Image,
    Submit,
    submit = Submit,
    Reset,
    reset = Reset,
    Button,
    button = Button
}
